name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build and test project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew build -x test
  
    - name: Publish result of unit test
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "build/test-result/test/**/*.xml"
        github_token: ${{ github.token }}
